# Generated by Django 3.1.7 on 2021-03-15 02:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Enter name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter description')),
            ],
            options={
                'ordering': ['name', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Enter name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter description')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('condition_rating', models.DecimalField(decimal_places=2, default=0, help_text='Enter condition rating from 0 to 5', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('condition_description', models.TextField(blank=True, help_text='Enter condition description')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer')),
                ('my_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
            ],
            options={
                'ordering': ['name', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('owner', models.CharField(help_text='Enter owner', max_length=100)),
                ('nation', models.CharField(help_text='Enter nation', max_length=100)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antartica'), ('AS', 'Asia'), ('EU', 'Europe'), ('OC', 'Oceania'), ('SA', 'South and Central America')], default='AS', max_length=2)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.record')),
            ],
            options={
                'ordering': ['-date_end'],
            },
        ),
    ]
