# Generated by Django 3.1.7 on 2021-03-14 23:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Enter name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter description')),
            ],
            options={
                'ordering': ['name', '-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Enter name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter description')),
                ('my_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
            ],
            options={
                'ordering': ['name', '-last_modified'],
                'abstract': False,
            },
        ),
    ]
