# Generated by Django 3.1.7 on 2021-02-26 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='The Unique ID of record', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter name/title of object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a short description of the object on record', null=True)),
                ('created', models.DateField(auto_now_add=True, help_text='Date of initial record creation')),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
