# Generated by Django 3.1.7 on 2021-02-26 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The Unique ID of record', primary_key=True, serialize=False),
        ),
    ]
